# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-20 06:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('client', 'client'), ('kitchen', 'kitchen')], max_length=7)),
                ('order', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.CharField(choices=[('new', 'new'), ('rendered', 'rendered'), ('printed', 'printed')], default='new', max_length=8)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdf/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('check_type', models.CharField(choices=[('client', 'client'), ('kitchen', 'kitchen')], max_length=7)),
                ('point_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='check',
            name='printer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forfar.Printer'),
        ),
    ]
